version: '3.4'

x-common: &common
  image: app-service:latest
  labels:
    com.app: app
  networks:
    - app
  volumes: &volumes
    - .:/app:delegated
    - build:/app/build/
    - ./node_modules:/app/node_modules/
    - node_dev:/usr/local/lib/node_modules/node-dev/

services:
  builder:
    volumes:
      - .:/app:delegated
      - build:/app/build/
      - ./node_modules:/app/node_modules/
    <<: *common
    image: app:latest
    container_name: app-builder
    command: [sh, -c, 'node build/tools/build.js && ./node_modules/.bin/tsc -w --pretty --skipLibCheck']

  js:
    image: app:latest
    volumes: *volumes
    networks:
      - app

  messaging-db:
    image: postgres:10-alpine
    environment:
      POSTGRES_DB: messaging
      POSTGRES_USER: messaging
      POSTGRES_PASSWORD: password
    networks:
      - app   

  spa:
    image: sethii/chat-spa-secure
    container_name: spa
    depends_on:
      - gateway
    networks:
      - app
    ports:
      - 3000:80

  gateway:
    <<: *common
    working_dir: /app/build
    container_name: gateway
    command: [sh, -c, 'node-dev ./services/gateway/src/index.js --configKey gateway']
    hostname: gateway  
    depends_on:
      - messaging
      - security

  messaging:
    <<: *common
    working_dir: /app/build
    container_name: messaging
    command: [sh, -c, 'node-dev ./services/messaging/src/index.js --configKey messaging']
    hostname: messaging 
    depends_on:
      - messaging-db

  security:
    <<: *common
    working_dir: /app/build
    container_name: security
    command: [sh, -c, 'node-dev ./services/security/src/index.js --configKey security']
    hostname: security

  integration-tests:
    <<: *common
    working_dir: /app/build
    command:
      [sh, -c, 'npm run integration-tests']
    depends_on:
      - gateway  

networks:
  app:

volumes:
  build:
  node_dev:
